# Generated by Django 3.1.3 on 2021-01-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='spec',
            field=models.FileField(default='spec_test.json', upload_to=''),
        ),
    ]
