# Generated by Django 3.1.3 on 2021-01-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_spec'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='endpoint',
            field=models.TextField(default={}, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='json_spec',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='profile',
            name='spec',
            field=models.FileField(default='spec_test.json', upload_to='spec_files'),
        ),
    ]
