# Generated by Django 3.1.3 on 2021-01-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210108_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='endpoint',
            field=models.TextField(max_length=50),
        ),
    ]
