# Generated by Django 3.1.3 on 2021-01-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210111_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='endpoint',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='json_spec',
            field=models.TextField(default=dict),
        ),
    ]
