# Generated by Django 3.1.3 on 2021-01-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210111_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='deletebool',
            field=models.BooleanField(default=0),
        ),
    ]
