# Generated by Django 3.1.3 on 2021-01-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_profile_deletebool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='deletebool',
            new_name='Intermittent_connection_issues',
        ),
        migrations.AddField(
            model_name='profile',
            name='connection_down',
            field=models.BooleanField(default=0),
        ),
    ]
