# Generated by Django 3.1.3 on 2021-01-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210118_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='endpoint',
            field=models.TextField(max_length=50, unique=True),
        ),
    ]
