# Generated by Django 3.1.3 on 2021-01-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210119_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='json_spec',
            field=models.JSONField(default=dict),
        ),
    ]
