# Generated by Django 3.1.3 on 2021-01-25 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20210121_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Intermittent_connection_per',
            field=models.IntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
