# Generated by Django 3.1.3 on 2021-01-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_profile_intermittent_connection_per'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='json_spec',
            field=models.TextField(default='[[{},{},200]]'),
        ),
    ]
